import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Common/Navbar/Navbar";
import TopWhiteNav from "./components/Common/Navbar/TopWhiteNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="mytheme" lang="en">
      <body className={inter.className}>
        <TopWhiteNav/>
        <Navbar/>
        {children}</body>
    </html>
  );
}
